### ISSUE TITLE
1.17

### ISSUE THREAD

**Issue by ayunami2000** [hhhzzzsss/SongPlayer#1]
i did it for you (lazy, didnt configure it to rename output file to not fabric-example-mod so i manually renamed it)

credit me in readme pls
~~[SongPlayer.zip](https://github.com/hhhzzzsss/SongPlayer/files/6681761/SongPlayer.zip)~~

**Comment by ayunami2000** [comment]
ok i made a repo https://github.com/ayunami2000/SongPlayer-1.17

**Comment by hhhzzzsss** [comment]
This repository is rather bare-bones and missing all of the gradle files, so it would probably be easier for me to update it from scratch, but thank you for going through the effort of updating it. If you make a fork of the repository and make a pull request, I'll accept your changes so that you would be listed as one of the contributors.

I was originally planning on updating this once totalfreedom updated to 1.17 anyway, so if you don't feel like it don't worry about it.

**Comment by ayunami2000** [comment]
can u just credit me in the readme once you update to 1.17

**Comment by hhhzzzsss** [comment]
Ah, my bad, I thought you were talking about being credited for the port.

Alright, you've been asking this for a while and my main reason for holding off, as I've said before, was that my implementation is not based on yours. It is a derivative of my older SongBot project and uses an entirely different framework from your bot. I have not used or referenced your code when creating SongPlayer.

However, I don't think this is worth arguing about any further, so how does this sound:

You were indeed the first person to create a functioning music bot that places noteblocks with preexisting nbt data such that it does not need to tune the noteblocks or place the correct blocks underneath them, so I will credit you with the original proof-of-concept of this mechanism. I will also add a link to your repl or repository if you provide me one. In order to explain what part of the mechanism is something you have implemented before me, I will add a section explaining the mechanism of the bot in more detail.

If you agree, I will update the readme as soon as I have time.

**Comment by ayunami2000** [comment]
I am talking about being credited for the port actually. I don't need
credit for the mechanism. That would be cool though, but not necessary.

**Comment by hhhzzzsss** [comment]
Oh, alright. I'll link your repo in my readme. I'll add a part on how you were the first to implement the mechanism as well anyway, since I already offered to. Does your old repl still exist?

**Comment by ayunami2000** [comment]
I have no memory but if you mean the kaboom bot then that is on glitch. I
don't remember the name of it though.

**Comment by hhhzzzsss** [comment]
Oh, okay. Well I'll be closing this issue then. The update will come as soon as I work out all the gradle issues.
