### ISSUE TITLE
add 1.21 support pls

### ISSUE THREAD

**Issue by RealIceCone** [hhhzzzsss/SongPlayer#47]
add 1.21 support pls

**Comment by circularsprojects** [comment]
> add 1.21 support pls

i can make a fork that's modified for 1.21 if you want

**Comment by RealIceCone** [comment]
> > add 1.21 support pls
> 
> i can make a fork that's modified for 1.21 if you want

Thank you

**Comment by hugo23070** [comment]
> > add 1.21 support pls
> 
> i can make a fork that's modified for 1.21 if you want

hey bro, can you tell me when you made it, cuz i've been trying to get it for 1.21 but can't find a way

**Comment by circularsprojects** [comment]
i made a fork with 1.21 support
https://github.com/circularsprojects/SongPlayer
now uhh its a little weird because i have two different forks so theyre on different branches so sorry if its a bit confusing
you can download the compiled jar under releases
small disclaimer i have no idea if these will fully work as intended, but in my experience theyve worked as intended 👍

**Comment by circularsprojects** [comment]
also i think its worth mentioning the main branch is mainly just experimental stuff ive done, so if you want to see just the base 1.21 mod, go to the "1.21-base" branch

**Comment by hugo23070** [comment]
> also i think its worth mentioning the main branch is mainly just experimental stuff ive done, so if you want to see just the base 1.21 mod, go to the "1.21-base" branch

ok thx, bro you are the goat my guy

**Comment by hhhzzzsss** [comment]
Updated
