### ISSUE TITLE
Noteblocks infinently placing in multiplayer

### ISSUE THREAD

**Issue by Radplayz** [hhhzzzsss/SongPlayer#62]
Seems that whenever I try to play a song, locally or through a link, it will just place blocks forever in a multiplayer server. Any fix?
![javaw_EP0Z4ZC6zO](https://github.com/user-attachments/assets/d7701c6b-c215-4921-ac66-57d2b4cd0aec)

**Comment by Radplayz** [comment]
The server is public, however creative mode is only for admins. Here is the plugin list
![firefox_Ga7PUBXKVA](https://github.com/user-attachments/assets/5c8112b5-6a72-4fa1-84d1-36331dc74b93)
And if you still want to attempt the server, its join.harmonyfallssmp.world

**Comment by Sk8kman** [comment]
for anyone looking at this issue, the problem is ItemsAdder hiding the "Instrument" property of the noteblock. This causes SongPlayer to keep replacing noteblocks with the proper instrument only for the plugin to overwrite it with harps. I'll probably work on a fix for this and make a pull request, but the only fix I can think of is making a toggle that will flat out ignore instrument properties, or check the block underneath rather than the blockstate in survival playmode.

**Comment by Radplayz** [comment]
Will contact ia to see if there can be a fix put out for this as well

**Comment by NoteBlockMR** [comment]
Noteblock can't use nbt because of a plugin called ItemsAdder
